version: '2.1'

services:
  angular-event-view-cli:
    image: johnpapa/angular-event-view-cli:latest
    environment:
      NODE_ENV: development
    build: .
    ports:
      - 80:80
      - 443:443
      - 9229:9229
